
export const LOAD_CLIENTS_REQUEST = 'LOAD_CLIENTS_REQUEST'
export const LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS'
export const LOAD_CLIENTS_ERROR = 'LOAD_CLIENTS_ERROR'

export const CHANGE_CLIENTS_FILTER = 'CHANGE_CLIENTS_FILTER'
export const SET_ACTIVE_CLIENT = 'SET_ACTIVE_CLIENT'